[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "composer",
  "git",
  "unzip",
  "nodejs_20",
  "yarn"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "yarn install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=3000"
